default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: quack_development

test:
  <<: *default
  database: quack_test
  
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
